// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(PortfolioDBContext))]
    [Migration("20260825134835_ExprienceData")]
    partial class ExprienceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Portfolio.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RolName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Experience", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "iCapps",
                            EndDate = new DateTime(2021, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            RolName = "Stagiair",
                            StartDate = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            WebsiteUrl = "https://www.icapps.com/"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Taglayer",
                            EndDate = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            RolName = "Fullstack developer",
                            StartDate = new DateTime(2021, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            WebsiteUrl = "https://taglayer.com/"
                        });
                });

            modelBuilder.Entity("Domain.Portfolio.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "vue.svg",
                            Level = 3,
                            Name = "Vue",
                            Tags = "[\"frontend\"]"
                        },
                        new
                        {
                            Id = 2,
                            Image = "react.svg",
                            Level = 1,
                            Name = "React",
                            Tags = "[\"fronted\"]"
                        },
                        new
                        {
                            Id = 3,
                            Image = "typescript.svg",
                            Level = 3,
                            Name = "TypeScript",
                            Tags = "[\"fullstack\",\"api\"]"
                        },
                        new
                        {
                            Id = 4,
                            Image = "tailwind.svg",
                            Level = 2,
                            Name = "Tailwind",
                            Tags = "[\"fronted\"]"
                        },
                        new
                        {
                            Id = 5,
                            Image = "dotnet.svg",
                            Level = 1,
                            Name = ".NET",
                            Tags = "[\"fullstack\",\"api\"]"
                        },
                        new
                        {
                            Id = 6,
                            Image = "docker.svg",
                            Level = 2,
                            Name = "Docker",
                            Tags = "[\"backend\"]"
                        },
                        new
                        {
                            Id = 7,
                            Image = "mongodb.svg",
                            Level = 3,
                            Name = "MongoDB",
                            Tags = "[\"backend\",\"database\"]"
                        },
                        new
                        {
                            Id = 8,
                            Image = "postgresql.svg",
                            Level = 2,
                            Name = "PostgreSQL",
                            Tags = "[\"backend\",\"database\"]"
                        });
                });

            modelBuilder.Entity("ExperienceSkill", b =>
                {
                    b.Property<int>("ExperiencesId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.HasKey("ExperiencesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("ExperienceSkill");

                    b.HasData(
                        new
                        {
                            ExperiencesId = 2,
                            SkillsId = 1
                        },
                        new
                        {
                            ExperiencesId = 1,
                            SkillsId = 2
                        },
                        new
                        {
                            ExperiencesId = 1,
                            SkillsId = 3
                        },
                        new
                        {
                            ExperiencesId = 2,
                            SkillsId = 3
                        },
                        new
                        {
                            ExperiencesId = 2,
                            SkillsId = 4
                        },
                        new
                        {
                            ExperiencesId = 2,
                            SkillsId = 6
                        },
                        new
                        {
                            ExperiencesId = 2,
                            SkillsId = 7
                        });
                });

            modelBuilder.Entity("ExperienceSkill", b =>
                {
                    b.HasOne("Domain.Portfolio.Experience", null)
                        .WithMany()
                        .HasForeignKey("ExperiencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Portfolio.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
