// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(PortfolioDBContext))]
    [Migration("20260819141428_ExtraSkillData")]
    partial class ExtraSkillData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Portfolio.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "vue.svg",
                            Level = 3,
                            Name = "Vue",
                            Tags = "[\"frontend\"]"
                        },
                        new
                        {
                            Id = 2,
                            Image = "react.svg",
                            Level = 1,
                            Name = "React",
                            Tags = "[\"fronted\"]"
                        },
                        new
                        {
                            Id = 3,
                            Image = "typescript.svg",
                            Level = 3,
                            Name = "TypeScript",
                            Tags = "[\"fullstack\",\"api\"]"
                        },
                        new
                        {
                            Id = 4,
                            Image = "tailwind.svg",
                            Level = 2,
                            Name = "Tailwind",
                            Tags = "[\"fronted\"]"
                        },
                        new
                        {
                            Id = 5,
                            Image = "dotnet.svg",
                            Level = 1,
                            Name = ".NET",
                            Tags = "[\"fullstack\",\"api\"]"
                        },
                        new
                        {
                            Id = 6,
                            Image = "docker.svg",
                            Level = 2,
                            Name = "Docker",
                            Tags = "[\"backend\"]"
                        },
                        new
                        {
                            Id = 7,
                            Image = "mongodb.svg",
                            Level = 3,
                            Name = "MongoDB",
                            Tags = "[\"backend\",\"database\"]"
                        },
                        new
                        {
                            Id = 8,
                            Image = "postgresql.svg",
                            Level = 2,
                            Name = "PostgreSQL",
                            Tags = "[\"backend\",\"database\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
